"""empty message

Revision ID: 0889a8a1d7d9
Revises: 32983e20e9a8
Create Date: 2016-12-14 19:55:43.860750

"""

# revision identifiers, used by Alembic.
revision = '0889a8a1d7d9'
down_revision = '32983e20e9a8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('update_key', sa.String(length=240), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'update_key')
    ### end Alembic commands ###
