"""empty message

Revision ID: 15b124674afe
Revises: 4bf1aea270d5
Create Date: 2017-05-31 12:58:52.298991

"""

# revision identifiers, used by Alembic.
revision = '15b124674afe'
down_revision = '4bf1aea270d5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('params',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload', sa.Integer(), nullable=True),
    sa.Column('regDate', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('params')
    # ### end Alembic commands ###
