"""empty message

Revision ID: 1c0cb1ea3518
Revises: cc0d678344b1
Create Date: 2016-12-14 19:41:46.395916

"""

# revision identifiers, used by Alembic.
revision = '1c0cb1ea3518'
down_revision = 'cc0d678344b1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('update_key', sa.String(length=60), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'update_key')
    ### end Alembic commands ###
