"""empty message

Revision ID: 2463083dc641
Revises: 95823d9aa7a4
Create Date: 2017-04-19 12:38:52.148923

"""

# revision identifiers, used by Alembic.
revision = '2463083dc641'
down_revision = '95823d9aa7a4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finscope',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('banked', sa.Integer(), nullable=True),
    sa.Column('other_formal', sa.Integer(), nullable=True),
    sa.Column('other_informal', sa.Integer(), nullable=True),
    sa.Column('excluded', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finscope')
    ### end Alembic commands ###
