"""empty message

Revision ID: 302baee6981f
Revises: cf1000f5fd95
Create Date: 2017-01-09 17:20:18.584718

"""

# revision identifiers, used by Alembic.
revision = '302baee6981f'
down_revision = 'cf1000f5fd95'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saving_group', sa.Column('district_name', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saving_group', 'district_name')
    ### end Alembic commands ###
