"""empty message

Revision ID: 32f83396ccfa
Revises: a3d51f920c28
Create Date: 2017-03-06 13:05:44.642724

"""

# revision identifiers, used by Alembic.
revision = '32f83396ccfa'
down_revision = 'a3d51f920c28'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'saving_group', 'sector', ['sector_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'saving_group', type_='foreignkey')
    ### end Alembic commands ###
