"""empty message

Revision ID: 34eaece8a1fd
Revises: ca2cec874e1b
Create Date: 2016-12-06 18:14:28.529006

"""

# revision identifiers, used by Alembic.
revision = '34eaece8a1fd'
down_revision = 'ca2cec874e1b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'files_user_id_fkey', 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'user', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.create_foreign_key(u'files_user_id_fkey', 'files', 'ngo', ['user_id'], ['id'])
    ### end Alembic commands ###
