"""empty message

Revision ID: 4dda3511c15a
Revises: 6c7591de7f80
Create Date: 2016-11-28 11:37:48.123413

"""

# revision identifiers, used by Alembic.
revision = '4dda3511c15a'
down_revision = '6c7591de7f80'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ngo', sa.Column('username', sa.String(length=30), nullable=True))
    op.create_unique_constraint(None, 'ngo', ['username'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ngo', type_='unique')
    op.drop_column('ngo', 'username')
    ### end Alembic commands ###
