"""empty message

Revision ID: 534e967d55bb
Revises: 6f73b5fffdf1
Create Date: 2017-02-02 13:05:37.212430

"""

# revision identifiers, used by Alembic.
revision = '534e967d55bb'
down_revision = '6f73b5fffdf1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('size', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'size')
    ### end Alembic commands ###
