"""empty message

Revision ID: 5850e27ce672
Revises: ef979c252b6a
Create Date: 2017-04-19 16:34:11.149641

"""

# revision identifiers, used by Alembic.
revision = '5850e27ce672'
down_revision = 'ef979c252b6a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finscope')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finscope',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('banked', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('other_formal', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('other_informal', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('excluded', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('district_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['district_id'], [u'district.id'], name=u'finscope_district_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'finscope_pkey')
    )
    ### end Alembic commands ###
