"""empty message

Revision ID: 59be0018c944
Revises: 0889a8a1d7d9
Create Date: 2017-01-03 12:59:15.445319

"""

# revision identifiers, used by Alembic.
revision = '59be0018c944'
down_revision = '0889a8a1d7d9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'names')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('names', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    ### end Alembic commands ###
