"""empty message

Revision ID: 5c69729d492f
Revises: 59be0018c944
Create Date: 2017-01-03 12:59:51.686510

"""

# revision identifiers, used by Alembic.
revision = '5c69729d492f'
down_revision = '59be0018c944'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('names', sa.String(length=140), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'names')
    ### end Alembic commands ###
