"""empty message

Revision ID: 6f73b5fffdf1
Revises: 611ba463d901
Create Date: 2017-01-31 12:28:57.626097

"""

# revision identifiers, used by Alembic.
revision = '6f73b5fffdf1'
down_revision = '611ba463d901'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('amount', sa.Column('uniq_id', sa.String(length=240), nullable=True))
    op.create_unique_constraint(None, 'amount', ['uniq_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'amount', type_='unique')
    op.drop_column('amount', 'uniq_id')
    ### end Alembic commands ###
