"""empty message

Revision ID: 72ad0938bd9f
Revises: 15b124674afe
Create Date: 2017-05-31 13:17:39.379894

"""

# revision identifiers, used by Alembic.
revision = '72ad0938bd9f'
down_revision = '15b124674afe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('params', sa.Column('signup', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('signup', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('upload', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'upload')
    op.drop_column('user', 'signup')
    op.drop_column('params', 'signup')
    # ### end Alembic commands ###
