"""empty message

Revision ID: 78c407b5f0a0
Revises: d026a23612e8
Create Date: 2017-01-26 16:42:01.494635

"""

# revision identifiers, used by Alembic.
revision = '78c407b5f0a0'
down_revision = 'd026a23612e8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sgs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('funding_id', sa.Integer(), nullable=True),
    sa.Column('sg_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sg_id'], ['saving_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'saving_group', 'partner_id')
    op.drop_column(u'saving_group', 'funding_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'saving_group', sa.Column('funding_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(u'saving_group', sa.Column('partner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('sgs')
    ### end Alembic commands ###
