"""empty message

Revision ID: 7ef35c35ff93
Revises: 9d04ae11c178
Create Date: 2017-01-27 16:28:25.145884

"""

# revision identifiers, used by Alembic.
revision = '7ef35c35ff93'
down_revision = '9d04ae11c178'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'saving_group_uniq_id_key', 'saving_group', type_='unique')
    op.drop_column('saving_group', 'uniq_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saving_group', sa.Column('uniq_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_unique_constraint(u'saving_group_uniq_id_key', 'saving_group', ['uniq_id'])
    ### end Alembic commands ###
