"""empty message

Revision ID: 887b0d8b4601
Revises: f8bdb411d73f
Create Date: 2017-01-12 00:30:18.187776

"""

# revision identifiers, used by Alembic.
revision = '887b0d8b4601'
down_revision = 'f8bdb411d73f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('distribution', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telco_agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('distribution', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_name', sa.String(length=100), nullable=True),
    sa.Column('financial_name', sa.String(length=100), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('population',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('male', sa.Integer(), nullable=True),
    sa.Column('female', sa.Integer(), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('population')
    op.drop_table('financial')
    op.drop_table('telco_agent')
    op.drop_table('bank_agent')
    ### end Alembic commands ###
