"""empty message

Revision ID: 8a857275969c
Revises: e4f3473320b7
Create Date: 2016-12-06 18:34:52.990017

"""

# revision identifiers, used by Alembic.
revision = '8a857275969c'
down_revision = 'e4f3473320b7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original', sa.String(length=175), nullable=True),
    sa.Column('saved', sa.String(length=175), nullable=True),
    sa.Column('filename', sa.String(length=150), nullable=True),
    sa.Column('regDate', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    ### end Alembic commands ###
