"""empty message

Revision ID: 8f79ed01a1ce
Revises: 4dda3511c15a
Create Date: 2016-12-05 16:47:52.819148

"""

# revision identifiers, used by Alembic.
revision = '8f79ed01a1ce'
down_revision = '4dda3511c15a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('names', sa.String(length=80), nullable=True),
    sa.Column('username', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('user_role', sa.Integer(), nullable=True),
    sa.Column('regDate', sa.DateTime(), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('job_title', sa.String(length=80), nullable=True),
    sa.Column('ngo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.drop_constraint(u'ngo_cp_email_key', 'ngo', type_='unique')
    op.drop_constraint(u'ngo_cp_telephone_key', 'ngo', type_='unique')
    op.drop_constraint(u'ngo_username_key', 'ngo', type_='unique')
    op.drop_column(u'ngo', 'username')
    op.drop_column(u'ngo', 'cp_email')
    op.drop_column(u'ngo', 'cp_name')
    op.drop_column(u'ngo', 'password')
    op.drop_column(u'ngo', 'cp_telephone')
    op.drop_constraint(u'sgs_funding_id_fkey', 'sgs', type_='foreignkey')
    op.drop_constraint(u'sgs_partner_id_fkey', 'sgs', type_='foreignkey')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(u'sgs_partner_id_fkey', 'sgs', 'ngo', ['partner_id'], ['id'])
    op.create_foreign_key(u'sgs_funding_id_fkey', 'sgs', 'ngo', ['funding_id'], ['id'])
    op.add_column(u'ngo', sa.Column('cp_telephone', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column(u'ngo', sa.Column('password', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column(u'ngo', sa.Column('cp_name', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.add_column(u'ngo', sa.Column('cp_email', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.add_column(u'ngo', sa.Column('username', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.create_unique_constraint(u'ngo_username_key', 'ngo', ['username'])
    op.create_unique_constraint(u'ngo_cp_telephone_key', 'ngo', ['cp_telephone'])
    op.create_unique_constraint(u'ngo_cp_email_key', 'ngo', ['cp_email'])
    op.drop_table('user')
    ### end Alembic commands ###
