"""empty message

Revision ID: 95823d9aa7a4
Revises: df5b62a0448c
Create Date: 2017-04-04 19:23:08.959010

"""

# revision identifiers, used by Alembic.
revision = '95823d9aa7a4'
down_revision = 'df5b62a0448c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mfi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('non_umurenge_sacco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('umurenge_sacco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'bank', sa.Column('count', sa.Integer(), nullable=True))
    op.add_column(u'bank', sa.Column('name', sa.String(length=100), nullable=True))
    op.drop_column(u'bank', 'branch_count')
    op.drop_column(u'bank', 'bank')
    op.add_column(u'bank_agent', sa.Column('count', sa.Integer(), nullable=True))
    op.drop_column(u'bank_agent', 'distribution')
    op.add_column(u'telco_agent', sa.Column('count', sa.Integer(), nullable=True))
    op.drop_column(u'telco_agent', 'distribution')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'telco_agent', sa.Column('distribution', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column(u'telco_agent', 'count')
    op.add_column(u'bank_agent', sa.Column('distribution', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column(u'bank_agent', 'count')
    op.add_column(u'bank', sa.Column('bank', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column(u'bank', sa.Column('branch_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column(u'bank', 'name')
    op.drop_column(u'bank', 'count')
    op.drop_table('umurenge_sacco')
    op.drop_table('non_umurenge_sacco')
    op.drop_table('mfi')
    ### end Alembic commands ###
