"""empty message

Revision ID: 9d04ae11c178
Revises: 78c407b5f0a0
Create Date: 2017-01-27 16:03:23.267023

"""

# revision identifiers, used by Alembic.
revision = '9d04ae11c178'
down_revision = '78c407b5f0a0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saving_group', sa.Column('uniq_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'saving_group_name_key', 'saving_group', type_='unique')
    op.create_unique_constraint(None, 'saving_group', ['uniq_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'saving_group', type_='unique')
    op.create_unique_constraint(u'saving_group_name_key', 'saving_group', ['name'])
    op.drop_column('saving_group', 'uniq_id')
    ### end Alembic commands ###
