"""empty message

Revision ID: a12f6c849290
Revises: e2f106e5f80e
Create Date: 2016-12-06 18:28:35.986925

"""

# revision identifiers, used by Alembic.
revision = 'a12f6c849290'
down_revision = 'e2f106e5f80e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original', sa.String(length=25), nullable=True),
    sa.Column('saved', sa.String(length=25), nullable=True),
    sa.Column('filename', sa.String(length=150), nullable=True),
    sa.Column('regDate', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('files')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('original', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    sa.Column('saved', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    sa.Column('filename', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('regDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'files_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'files_pkey')
    )
    op.drop_table('user_files')
    ### end Alembic commands ###
