"""empty message

Revision ID: a3d51f920c28
Revises: 534e967d55bb
Create Date: 2017-03-06 13:02:05.740682

"""

# revision identifiers, used by Alembic.
revision = 'a3d51f920c28'
down_revision = '534e967d55bb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('amount')
    op.drop_table('sgs')
    op.add_column('saving_group', sa.Column('borrowing', sa.Float(), nullable=True))
    op.add_column('saving_group', sa.Column('funding_id', sa.Integer(), nullable=True))
    op.add_column('saving_group', sa.Column('partner_id', sa.Integer(), nullable=True))
    op.add_column('saving_group', sa.Column('saving', sa.Float(), nullable=True))
    op.add_column('saving_group', sa.Column('year_of_creation', sa.Integer(), nullable=True))
    op.drop_constraint(u'saving_group_uniq_id_key', 'saving_group', type_='unique')
    op.create_foreign_key(None, 'saving_group', 'ngo', ['funding_id'], ['id'])
    op.create_foreign_key(None, 'saving_group', 'ngo', ['partner_id'], ['id'])
    op.drop_column('saving_group', 'uniq_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saving_group', sa.Column('uniq_id', sa.VARCHAR(length=240), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'saving_group', type_='foreignkey')
    op.drop_constraint(None, 'saving_group', type_='foreignkey')
    op.create_unique_constraint(u'saving_group_uniq_id_key', 'saving_group', ['uniq_id'])
    op.drop_column('saving_group', 'year_of_creation')
    op.drop_column('saving_group', 'saving')
    op.drop_column('saving_group', 'partner_id')
    op.drop_column('saving_group', 'funding_id')
    op.drop_column('saving_group', 'borrowing')
    op.create_table('sgs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('partner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('funding_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sg_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sg_id'], [u'saving_group.id'], name=u'sgs_sg_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'sgs_pkey')
    )
    op.create_table('amount',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('saving', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('borrowing', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sg_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uniq_id', sa.VARCHAR(length=240), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sg_id'], [u'saving_group.id'], name=u'amount_sg_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'amount_pkey'),
    sa.UniqueConstraint('uniq_id', name=u'amount_uniq_id_key')
    )
    ### end Alembic commands ###
