"""empty message

Revision ID: aa655a6f9f96
Revises: 67c719301d23
Create Date: 2017-04-04 16:19:54.320343

"""

# revision identifiers, used by Alembic.
revision = 'aa655a6f9f96'
down_revision = '67c719301d23'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank', sa.Column('branch_count', sa.String(length=100), nullable=True))
    op.drop_column('bank', 'branch_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank', sa.Column('branch_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('bank', 'branch_count')
    ### end Alembic commands ###
