"""empty message

Revision ID: b5b133138711
Revises: b6edc697cdb6
Create Date: 2017-04-03 18:21:25.141818

"""

# revision identifiers, used by Alembic.
revision = 'b5b133138711'
down_revision = 'b6edc697cdb6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_name', sa.String(length=100), nullable=True),
    sa.Column('bank', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('financial')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('branch_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('financial_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('sector_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sector_id'], [u'sector.id'], name=u'financial_sector_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'financial_pkey')
    )
    op.drop_table('banks')
    ### end Alembic commands ###
