"""empty message

Revision ID: b9195e09313b
Revises: 4a450c69842b
Create Date: 2016-11-23 17:48:02.867330

"""

# revision identifiers, used by Alembic.
revision = 'b9195e09313b'
down_revision = '4a450c69842b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funding', sa.Column('password', sa.String(length=50), nullable=True))
    op.add_column('partner', sa.Column('password', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partner', 'password')
    op.drop_column('funding', 'password')
    ### end Alembic commands ###
