"""empty message

Revision ID: ca2cec874e1b
Revises: 8f79ed01a1ce
Create Date: 2016-12-06 14:20:01.029942

"""

# revision identifiers, used by Alembic.
revision = 'ca2cec874e1b'
down_revision = '8f79ed01a1ce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original', sa.String(length=25), nullable=True),
    sa.Column('saved', sa.String(length=25), nullable=True),
    sa.Column('filename', sa.String(length=150), nullable=True),
    sa.Column('regDate', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['ngo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    ### end Alembic commands ###
