"""empty message

Revision ID: cc0d678344b1
Revises: 8a857275969c
Create Date: 2016-12-07 19:17:37.365159

"""

# revision identifiers, used by Alembic.
revision = 'cc0d678344b1'
down_revision = '8a857275969c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'saving_group', ['name'])
    op.add_column('sgs', sa.Column('sg_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sgs', 'sg_id')
    op.drop_constraint(None, 'saving_group', type_='unique')
    ### end Alembic commands ###
