"""empty message

Revision ID: cc3dd926366c
Revises: d0d725ab6291
Create Date: 2017-01-26 10:55:32.010828

"""

# revision identifiers, used by Alembic.
revision = 'cc3dd926366c'
down_revision = 'd0d725ab6291'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saving_group', sa.Column('sg_status', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saving_group', 'sg_status')
    ### end Alembic commands ###
