"""empty message

Revision ID: cf1000f5fd95
Revises: None
Create Date: 2017-01-04 11:00:22.657296

"""

# revision identifiers, used by Alembic.
revision = 'cf1000f5fd95'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ngo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('website', sa.String(length=60), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('picture', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('saving_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('member_female', sa.Integer(), nullable=True),
    sa.Column('member_male', sa.Integer(), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('sector_name', sa.String(length=100), nullable=True),
    sa.Column('regDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sgs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('funding_id', sa.Integer(), nullable=True),
    sa.Column('sg_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('amount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saving', sa.Float(), nullable=True),
    sa.Column('borrowing', sa.Float(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('sg_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sg_id'], ['saving_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('names', sa.String(length=80), nullable=True),
    sa.Column('username', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('user_role', sa.Integer(), nullable=True),
    sa.Column('regDate', sa.DateTime(), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('update_key', sa.String(length=240), nullable=True),
    sa.Column('job_title', sa.String(length=80), nullable=True),
    sa.Column('ngo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original', sa.String(length=175), nullable=True),
    sa.Column('saved', sa.String(length=175), nullable=True),
    sa.Column('filename', sa.String(length=150), nullable=True),
    sa.Column('regDate', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    op.drop_table('user')
    op.drop_table('amount')
    op.drop_table('sgs')
    op.drop_table('saving_group')
    op.drop_table('ngo')
    ### end Alembic commands ###
