"""empty message

Revision ID: d026a23612e8
Revises: cc3dd926366c
Create Date: 2017-01-26 15:48:33.159590

"""

# revision identifiers, used by Alembic.
revision = 'd026a23612e8'
down_revision = 'cc3dd926366c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sgs')
    op.add_column('saving_group', sa.Column('funding_id', sa.Integer(), nullable=True))
    op.add_column('saving_group', sa.Column('partner_id', sa.Integer(), nullable=True))
    op.drop_column('saving_group', 'district_name')
    op.drop_column('saving_group', 'sector_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saving_group', sa.Column('sector_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('saving_group', sa.Column('district_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('saving_group', 'partner_id')
    op.drop_column('saving_group', 'funding_id')
    op.create_table('sgs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('partner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('funding_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sg_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'sgs_pkey')
    )
    ### end Alembic commands ###
