"""empty message

Revision ID: df5b62a0448c
Revises: 8d62bddb0615
Create Date: 2017-04-04 16:21:19.153347

"""

# revision identifiers, used by Alembic.
revision = 'df5b62a0448c'
down_revision = '8d62bddb0615'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank', sa.Column('branch_count', sa.Integer(), nullable=True))
    op.drop_column('bank', 'branch_counts')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank', sa.Column('branch_counts', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('bank', 'branch_count')
    ### end Alembic commands ###
