"""empty message

Revision ID: e2f106e5f80e
Revises: f6f689466c35
Create Date: 2016-12-06 18:27:33.573638

"""

# revision identifiers, used by Alembic.
revision = 'e2f106e5f80e'
down_revision = 'f6f689466c35'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original', sa.String(length=25), nullable=True),
    sa.Column('saved', sa.String(length=25), nullable=True),
    sa.Column('filename', sa.String(length=150), nullable=True),
    sa.Column('regDate', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    ### end Alembic commands ###
